# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  client:
    image: paper-submission-system-client
    build:
      context: ./client
      dockerfile: Containerfile
    container_name: paper-submission-system-client
    ports:
      - 21743:80
    # 允许容器访问主机上的服务
    extra_hosts:
      - "host.docker.internal:host-gateway"

  server:
    image: paper-submission-system-server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: paper-submission-system-server
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_USER: Zajac
      DB_PASSWORD: 12345
      DB_NAME: paper_submission_system
      DB_PORT: 3306
      JWT_SECRET: c85d721ba95fcd5b3c63d32860620ba23dd06bc94a25ef3c11e89c351e17318b
      JWT_EXPIRES_IN: 24h
    ports:
      - 5000:5000
    # 允许容器访问主机上的服务
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 挂载volume用于文件上传
    volumes:
      - submitted-papers:/var/lib/submitted_papers
  

# 定义volume
volumes:
  submitted-papers:
  
